/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  '/api/calendar/events': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Get a user's calendar events
     * @description Returns all appointments for the given user for the time span from now until one month in the future.
     */
    get: operations['getEvents'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    /** @description A single calendar event/appointment */
    CalendarEvent: {
      /** @description Title of the appointment */
      title: string;
      /**
       * @description Start time of the appointment (ISO-8601 format, from LocalDateTime)
       * @example 2026-07-03T09:00:00
       */
      start: string;
      /**
       * @description End time of the appointment (ISO-8601 format, from LocalDateTime)
       * @example 2026-07-03T10:00:00
       */
      end: string;
      /** @description Location of the appointment */
      location: string;
      /** @description Description of the appointment */
      description: string;
    };
  };
  responses: never;
  parameters: {
    /** @description ID of the user whose calendar events should be retrieved */
    UserId: number;
  };
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
  getEvents: {
    parameters: {
      query: {
        /** @description ID of the user whose calendar events should be retrieved */
        userId: components['parameters']['UserId'];
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description List of calendar events within the requested time span */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['CalendarEvent'][];
        };
      };
      /** @description Invalid request parameters */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
}
