name: Vite React Typescript
on:
  pull_request:
  push:
    branches:
      - "main"

jobs:
  dependency-check:
    name: Dependency Check
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v7

      - name: Run Trivy Vulnerability Scan
        uses: aquasecurity/trivy-action@v0.36.0
        with:
          scan-type: fs
          image-ref: '.'
          format: json
          output: trivy-results.json
          severity: UNKNOWN,LOW,MEDIUM,HIGH,CRITICAL
          exit-code: '0'

      - name: Evaluate Vulnerabilities
        run: |
          count=$(jq '[.Results[]?.Vulnerabilities[]?] | length' trivy-results.json)

          cat trivy-results.json | jq -r '
            .Results[]?.Vulnerabilities[]? |
            "\(.Severity)|\(.PkgName)|\(.InstalledVersion)|\(.FixedVersion // "no fix")|\(.VulnerabilityID)"
          ' | while IFS="|" read -r severity pkg installed fixed cve; do
            case "$severity" in
              CRITICAL) color="\e[35m" ;;  # Magenta
              HIGH)     color="\e[31m" ;;  # rot
              MEDIUM)   color="\e[33m" ;;  # gelb
              LOW)      color="\e[34m" ;;  # blau
            esac
            link="https://nvd.nist.gov/vuln/detail/${cve}"
            echo -e "${color}[${severity}]\e[0m ${pkg}\n\t${installed} -> ${fixed}\n\t${cve} (${link})\n"
          done

          if [ "$count" -gt 0 ]; then
            echo "::warning::Found $count vulnerabilities. See report above."
            exit 1
          else
            echo "No vulnerabilities found."
          fi

  lint_typescript:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v7

      - uses: pnpm/action-setup@v6
        with:
          version: 11

      - name: Check format
        run: pnpm format:check
